export const SET_RECORD = "SET_RECORD";
export const GET_PEOPLE = "GET_PEOPLE";
export const DELETE_ONE_RECORD = `DELETE_ONE_RECORD`;
export const CREATE_ONE_RECORD = `CREATE_ONE_RECORD`;
export const UPDATE_ONE_RECORD = `UPDATE_ONE_RECORD`;
export const FETCH_RECORDS = `FETCH_RECORDS`;
